apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
    containers:
    - name: api
      image: max003003003/quotes-back:v1
      ports:
      - name: api-port
        containerPort: 5000
        protocol: TCP