apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: eon01/quotes-back:v1
        name: api
        ports:
        - containerPort: 3000
          name: http
        env:
          - name: SQLALCHEMY_DATABASE_URI
            value: "mysql+pymysql://root:root@data:3306/mydatabase"